spring.application.name=TaskTimeTracker

spring.datasource.url=jdbc:postgresql://localhost:5432/task_tracker
spring.datasource.username=dev
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration


